### ISSUE TITLE
Can I use this lib to server-side routing?

### ISSUE THREAD

**Issue by PaulMaly** [MartinKolarik/ractive-route#4]
I use RactiveJS to render templates on the server-side too. Can I use ractive-route in NodeJs server just like on the client-side?

**Comment by MartinKolarik** [comment]
Not yet. I originally made ractive-route to ease the handling of state changes and various events that only happen in the browser. I've been planning a complete rewrite of this library (which will bring several new features, including server-side support) for about a year now, but there has always been something more important and I have no ETA when I'm going to release it.

However, it *is* possible to use this library even when you need server-side rendering. I usually use [ractive-render](https://github.com/MartinKolarik/ractive-render) and load component files based on the URL, so I actually don't need any "routing". Small example:
```
/ -> loads views/index.html
/about -> loads views/about.html
/user/settings -> loads /views/user/settings.html
```

Obviously, for this to work, your directory and URL structure must be the same but I like to organize the code like that anyway.

If you need something more advanced, express.js uses similar syntax for route definitions, so it should be easy to use that as well.

**Comment by PaulMaly** [comment]
Thanks for the answer, Martin! But, seems, it's not solution for me, because I try to make my code isomorphic as it possible. 

So, I already in progress to integrate Director (isomorphic router) with Ractive. I just found your lib today and I've thought perhaps it'll be better for me. It's a pity that it not so. Good luck with development of this lib, maybe I'll check it progress from time to time. 

Thanks!
