### ISSUE TITLE
jumping directly to Url does not work

### ISSUE THREAD

**Issue by wadimdementjew** [MartinKolarik/ractive-route#5]
Example:
[https://raw.githubusercontent.com/MartinKolarik/ractive-route/master/demo/credits](https://raw.githubusercontent.com/MartinKolarik/ractive-route/master/demo/credits)
click the link, it results directly in an 404

**Comment by MartinKolarik** [comment]
That's just in the demo. Obviously your server needs to send the correct file for all URLs and GitHub can't do that.

**Comment by wadimdementjew** [comment]
the correct file?????
in an javascript frontend? ist hat not the function of an router, to serve the correct conmination of uri and webcontent?
